### ISSUE TITLE
Issue in logistic regression

### ISSUE THREAD

**Issue by nitin456** [aymericdamien/TensorFlow-Examples#10]
Hi,

avg_cost += sess.run(cost, feed_dict={x: batch_xs, y: batch_ys})/total_batch

Why do you divide the cose with total_batch. I think you should first divide the cost with batch_size and then after tool divide it again with total_batch. 

Thanks,
Nitin

**Comment by aymericdamien** [comment]
Hi, you are right, I forgot to compute the mean loss over a batch. It is not a problem with small batch size, but it could lead to issues with large batch size, as it leads to unrepresentative cost (NaN) ...
I will correct it soon, thanks for reporting the issue!
