### ISSUE TITLE
Porting Model to Android

### ISSUE THREAD

**Issue by shoaibahmed** [aymericdamien/TensorFlow-Examples#11]
Hi,

Thanks for such wonderful tutorials. I would like to port the Bi-Directional LSTM model trained on a GPU to Android. Can you pl add a sample for it?

**Comment by aymericdamien** [comment]
Hi, sorry I am not so familiar with Android environment.. I prefer focus on python examples for now. I think you can have a look at TensorFlow C++ code, but it seems that unfortunately rnn cell is not yet implemented, so you would need to replicate rnn and rnn_cell from python to C++

**Comment by shoaibahmed** [comment]
Ok. Thanks.

**Comment by spaul13** [comment]
@shoaibahmed do you succeed in implementing and running the bidirectional lstm benchmark on android? If yes, can u please help me with the steps?
