### ISSUE TITLE
Variable-Length Bi-Directional RNN

### ISSUE THREAD

**Issue by gessulat** [aymericdamien/TensorFlow-Examples#12]
Hi,
and thank you so much for this examples. These are all very helpful and demonstrate the core ideas of the models very well! 

I am still new to Tensorflow and RNN training and am currently wondering, how to deal with input series that has variable length. I found this example on [reddit] (https://www.reddit.com/r/MachineLearning/comments/3sok8k/tensorflow_basic_rnn_example_with_variable_length/) and it seems it uses padding to bring sequences to the same length. Unfortunately, I cannot make that particular example run.

Would it be possible to provide an example?

Thanks and best,
Sigi

**Comment by aymericdamien** [comment]
Hi, for me their example is just working fine! You can provide different values for early_stop, the timestep you want to stop at. Maybe make sure you are using tensorflow 0.6.0.

```
import tensorflow as tf
from tensorflow.models.rnn import rnn
from tensorflow.models.rnn.rnn_cell import BasicLSTMCell, LSTMCell
import numpy as np

if __name__ == '__main__':
  np.random.seed(1)
  size = 100
  batch_size= 100
  n_steps = 45
  seq_width = 50

  initializer = tf.random_uniform_initializer(-1,1)

  seq_input = tf.placeholder(tf.float32, [n_steps, batch_size, seq_width])
    #sequence we will provide at runtime  
  early_stop = tf.placeholder(tf.int32)
    #what timestep we want to stop at

  inputs = [tf.reshape(i, (batch_size, seq_width)) for i in tf.split(0, n_steps, seq_input)]
    #inputs for rnn needs to be a list, each item being a timestep. 
    #we need to split our input into each timestep, and reshape it because split keeps dims by default  

  cell = LSTMCell(size, seq_width, initializer=initializer)
  initial_state = cell.zero_state(batch_size, tf.float32)
  outputs, states = rnn.rnn(cell, inputs, initial_state=initial_state, sequence_length=early_stop)
    #set up lstm

  iop = tf.initialize_all_variables()
    #create initialize op, this needs to be run by the session!
  session = tf.Session()
  session.run(iop)

  for e_s in [10, 100, 200, 250]:
    feed = {early_stop:e_s, seq_input:np.random.rand(n_steps, batch_size, seq_width).astype('float32')}
    outs = session.run(outputs, feed_dict=feed)
    print len(outs)

```

**Comment by monikkinom** [comment]
Have a look at https://danijar.com/variable-sequence-lengths-in-tensorflow/

**Comment by bstriner** [comment]
Hi! For a faster implementation using CuDNN, check this out: https://github.com/tensorflow/tensorflow/pull/22308
