### ISSUE TITLE
convolution parameter

### ISSUE THREAD

**Issue by rajendraranabhat** [aymericdamien/TensorFlow-Examples#13]
Hi in your convolutional_network.ipynb file. Do you mind how you come with the number of 7*7*64 in 
'wd1': tf.Variable(tf.random_normal([7*7*64, 1024])) . I am still confuse as how you are calculating this number. I think it is not arbitary number right?

**Comment by aymericdamien** [comment]
Yes, it is calculated based on the previous layer, to know total number of parameters. Basically, you have:
input: (28, 28, 1) Pictures of size 28x28 with 1 color channel (grayscale)
conv1, 32 filters, strides=1: 
(28, 28, 32)
maxpool1, kernel_size=2, strides=1: 
(14, 14, 32)
conv2, 64 filters, strides=1: 
(14, 14, 64)
maxpool2, kernel_size=2, strides=1: 
(7, 7, 64) => 7*7*64 outputs
(that we flatten to connect to a dense layer)
(3136)

For further understanding, you can have a look at http://cs231n.github.io/convolutional-networks/, it gives a good explanation and some examples.

**Comment by rajendraranabhat** [comment]
Thankyou.
