### ISSUE TITLE
“multiply” spelling mistake into “muliply”

### ISSUE THREAD

**Issue by MichaelShu3333** [aymericdamien/TensorFlow-Examples#137]
“multiply” spelling mistake into “muliply”in line 33 in examples/1_Introduction/basic_operations.py.
That cause the following output result:

a=2, b=3
Addition with constants: 5
Multiplication with constants: 6
Traceback (most recent call last):
  File "basic_operations.py", line 33, in <module>
    mul = tf.muliply(a, b)
AttributeError: module 'tensorflow' has no attribute 'muliply'

**Comment by aymericdamien** [comment]
Thankd for reporting this issue, it has been fix
