### ISSUE TITLE
Multi-Layer BDLSTM

### ISSUE THREAD

**Issue by shoaibahmed** [aymericdamien/TensorFlow-Examples#15]
Hi,
Thanks for such awesome tutorials. You have included a BDLSTM example. I would like to know how can we create a multi-layer BDLSTM model with non-linearities in between.

**Comment by aymericdamien** [comment]
You need to apply activation for every output for every RNN layer. here: https://github.com/aymericdamien/TensorFlow-Examples/blob/master/examples/3%20-%20Neural%20Networks/bidirectional_rnn.py#L84 you can change return function to return a list of all outputs with activation, that should give you something like:
```
time_dist_output = []
for output in outputs:
    time_dist_output.append(tf.your_activation(tf.matmul(output, _weights['out']) + _biases['out'])))
return res
```

**Comment by shoaibahmed** [comment]
Thanks

**Comment by shoaibahmed** [comment]
Thanks
