### ISSUE TITLE
logistic_regression.ipynb assumes input_data is available

### ISSUE THREAD

**Issue by danbri** [aymericdamien/TensorFlow-Examples#20]
Perhaps your jupyter notebook setup is different, but for me 
https://github.com/aymericdamien/TensorFlow-Examples/blob/master/notebooks/2%20-%20Basic%20Classifiers/logistic_regression.ipynb fails unless I copy in input_data from the NN notebook nearby, i.e. 

    cp 3\ -\ Neural\ Networks/input_data.py 2\ -\ Basic\ Classifiers/

**Comment by aymericdamien** [comment]
Thanks! I will add it.
