### ISSUE TITLE
How to fit my own dataset

### ISSUE THREAD

**Issue by rihun** [aymericdamien/TensorFlow-Examples#21]
Dear Aymeric

I am following ur work. You use MNIST data set for your work.
My question is how I can use my own dataset and fit it to your coding.

Please help me regarding this. 

Thanks and Regards
Nahid

**Comment by aymericdamien** [comment]
It depends what kind of data you want to use (sequence, image, features...). You need to format your dataset as a numpy array.
For such network https://github.com/aymericdamien/TensorFlow-Examples/blob/master/examples/3%20-%20Neural%20Networks/multilayer_perceptron.py, you can use:
X (your data): 2-D numpy array, with shape: [number_of_samples, features] 
Y (your data labels): 2-D array (An array of binary arrays; for class "1" out of a total of 5 classes: [0, 1, 0, 0, 0]) with shape [number_of_samples, labels_binary_array]

But it woulds required some changes: 
```
batch_xs, batch_ys = mnist.train.next_batch(batch_size)
```
You can change this line to instead return a batch of your own data (with shapes as above).

If you data are not so large, maybe you don't need batch, and can directly feed all data:
```
xs, ys = YOUR_DATA, YOUR_LABELS

with tf.Session() as sess:
    sess.run(init)

    # Training cycle
    for epoch in range(training_epochs):
        cost = 0.
        # Fit training using batch data
        sess.run(optimizer, feed_dict={x: xs, y: ys})
        # Compute average loss
        cost = sess.run(cost, feed_dict={x: xs, y: ys})
        # Display logs per epoch step
        if epoch % display_step == 0:
            print "Epoch:", '%04d' % (epoch+1), "cost=", "{:.9f}".format(cost)

    print "Optimization Finished!"
```

**Comment by rihun** [comment]
Thanks.
It is really very helpful to me.




Regards
 Nahid

**Comment by rihun** [comment]
Hi

I did my programme as follows.

................................................................................................................
# Import MINST data
#import input_data
#mnist = input_data.read_data_sets("/tmp/data/", one_hot=True)

import tensorflow as tf
from numpy import genfromtxt
mnist_data=genfromtxt('data_1.csv', delimiter=',')
mnist_label=genfromtxt('Level_1.csv', delimiter=',')


# Parameters
learning_rate = 0.001
training_epochs = 15
batch_size = 100
display_step = 1

# Network Parameters
n_hidden_1 = 64 # 1st layer num features
n_hidden_2 = 64 # 2nd layer num features
n_input = 9 # MNIST data input (img shape: 28*28)
n_classes = 2 # MNIST total classes (0-9 digits)

# tf Graph input
x = tf.placeholder("float", [None, n_input])
y = tf.placeholder("float", [None, n_classes])

# Create model
def multilayer_perceptron(_X, _weights, _biases):
    layer_1 = tf.nn.relu(tf.add(tf.matmul(_X, _weights['h1']),
_biases['b1'])) #Hidden layer with RELU activation
    layer_2 = tf.nn.relu(tf.add(tf.matmul(layer_1, _weights['h2']),
_biases['b2'])) #Hidden layer with RELU activation
    return tf.matmul(layer_2, _weights['out']) + _biases['out']

# Store layers weight & bias
weights = {
    'h1': tf.Variable(tf.random_normal([n_input, n_hidden_1])),
    'h2': tf.Variable(tf.random_normal([n_hidden_1, n_hidden_2])),
    'out': tf.Variable(tf.random_normal([n_hidden_2, n_classes]))
}
biases = {
    'b1': tf.Variable(tf.random_normal([n_hidden_1])),
    'b2': tf.Variable(tf.random_normal([n_hidden_2])),
    'out': tf.Variable(tf.random_normal([n_classes]))
}

# Construct model
pred = multilayer_perceptron(x, weights, biases)

# Define loss and optimizer
cost = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(pred, y)) #
Softmax loss
optimizer =
tf.train.AdamOptimizer(learning_rate=learning_rate).minimize(cost) # Adam
Optimizer
# Initializing the variables
xs, ys = mnist_data, mnist_label

init = tf.initialize_all_variables()
 with tf.Session() as sess:
      sess.run(init)
 # Training cycle
    for epoch in range(training_epochs):
        cost = 0.
        # Fit training using batch data
        sess.run(optimizer, feed_dict={x: xs, y: ys})
        # Compute average loss
        cost = sess.run(cost, feed_dict={x: xs, y: ys})
        # Display logs per epoch step
        if epoch % display_step == 0:
            print "Epoch:", '%04d' % (epoch+1), "cost=",
"{:.9f}".format(cost)

    print "Optimization Finished!"


......................................................................................................................................


But I got the following error.


  File "<ipython-input-53-5c0c095571d4>", line 55    with tf.Session()
as sess:    ^   IndentationError: unexpected indent



Here I attach my data file and Labels file. Could you please help me to
solve it.

Thanks and regrads
Nahid
