### ISSUE TITLE
retrieving weights in the autoencoder.py

### ISSUE THREAD

**Issue by asgharrazavi** [aymericdamien/TensorFlow-Examples#215]
After training the autoencoder, how could one get the final values of the weights and biases?

`print tf.Variable(weights['encoder_h1'])`
`<tf.Variable 'Variable_154:0' shape=(55, 60) dtype=float32_ref>`

How can I get the actual weight matrix as a numpy array?

**Comment by SharangC96** [comment]
you have to run it in a session.

with tf.Session() as sess:
    print sess.run(tf.Variable(weights['encoder_h1']))

**Comment by asgharrazavi** [comment]
Thanks. I also figures that I can use "sess =  tf.Session()" instead of "with tf.Session() as sess:" and then get weights by "w = sess.run(weights)".
