### ISSUE TITLE
Running random_forest.py gives error

### ISSUE THREAD

**Issue by shreyas-7** [aymericdamien/TensorFlow-Examples#218]
On copy-pasting the code of random_forest.py on Mac OSX, python3.6 and running gives the following error

    Extracting /tmp/data/train-images-idx3-ubyte.gz
    Extracting /tmp/data/train-labels-idx1-ubyte.gz
    Extracting /tmp/data/t10k-images-idx3-ubyte.gz
    Extracting /tmp/data/t10k-labels-idx1-ubyte.gz
    Traceback (most recent call last):
      File "random_forest.py", line 51, in <module>
        infer_op, _, _ = forest_graph.inference_graph(X)
      File "/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 476, in __iter__
        raise TypeError("'Tensor' object is not iterable.")
    TypeError: 'Tensor' object is not iterable.

**Comment by aymericdamien** [comment]
You need the latest version of TensorFlow to run this example (v1.4)

**Comment by shreyas-7** [comment]
There was some error in other task due to which I had downgraded from 1.4 to 1.3, upgrading again works. Thanks for your time.

**Comment by Anouar7995** [comment]
Please we can not solve this problem without  upgrading to 1.4 ?
