### ISSUE TITLE
tf.nn.sparse_softmax_cross_entropy_with_logits & "ValueError: Rank mismatch: Rank of labels (received 2) should equal rank of logits minus 1 (received 2).

### ISSUE THREAD

**Issue by lhyfst** [aymericdamien/TensorFlow-Examples#224]
if you use tensorflow 1.20 ,you maight be get this error "ValueError: Rank mismatch: Rank of labels (received 2) should equal rank of logits minus 1 (received 2).
",when you use tf.nn.sparse_softmax_cross_entropy_with_logits function.

my solution is changing "    loss_op = tf.reduce_mean(tf.nn.sparse_softmax_cross_entropy_with_logits(
        logits=logits, labels=tf.cast(labels, dtype=tf.int32)))"
to "loss_op = tf.reduce_mean(tf.nn.sparse_softmax_cross_entropy_with_logits(
        logits=logits_train, labels=tf.argmax(tf.cast(labels, dtype=tf.int32),1)))"

and then 
changing "acc_op = tf.metrics.accuracy(labels=labels, predictions=pred_classes)"
to "acc_op = tf.metrics.accuracy(labels=tf.argmax(tf.cast(labels, dtype=tf.int32),1),
                                 predictions=pred_classes)"

good luck!

**Comment by freckletonj** [comment]
Or replace the logits op with the following, swapping in [tf.nn.softmax_cross_entropy_with_logits](https://stackoverflow.com/questions/37312421/tensorflow-whats-the-difference-between-sparse-softmax-cross-entropy-with-logi):

```python
    loss_op = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(
        logits=logits, labels=labels))
```

**Comment by SahanaRamnath** [comment]
Also, in acc_op, replace ```labels=labels``` with ```labels=tf.argmax(labels,axis=1)``` since labels(mnist.train.labels or mnist.test.labels) is a num_samples x num_classes size matrix and [tf,metrics.accuracy](https://www.tensorflow.org/api_docs/python/tf/metrics/accuracy) expects a 1D-array containing the labels.

**Comment by shan1322** [comment]
still gives same error after removing tf.cast

**Comment by zhb1207** [comment]
I changed the loss_op to tf.nn.softmax_cross_entropy_with_logits, then I saw:

ValueError: Can not squeeze dim[1], expected a dimension of 1, got 10 for remove_squeezable_dimensions/Squeeze' (op: 'Squeeze') with input shapes: [128,10].

Or if I just modify the loss_op with tf.argmax, but not change the acc_op, the Error above also appears.
Emmm... so what's going wrong here?

**Comment by VasileiosPaps** [comment]
Check the dimensions of the target value y, I fixed it by just removing its second dimension : 
y = tf.placeholder(dtype=tf.int32, shape = (None), name = 'target')) instead of 
y = tf.placeholder(dtype=tf.int32, shape = (None,1 ), name = 'target'))
