### ISSUE TITLE
TensorFlow link on main page needs to be updated

### ISSUE THREAD

**Issue by f0rtyseven** [aymericdamien/TensorFlow-Examples#227]
The link https://tensorflow.org gives HTTPS certificate error. It needs to be updated to https://www.tensorflow.org/.
Please see the screenshots: (Checked on both Google Chrome and Firefox)
![image](https://user-images.githubusercontent.com/14765535/35624372-d074eee0-06b4-11e8-9ecd-856ca24b59db.png)
![image](https://user-images.githubusercontent.com/14765535/35624394-e18ea518-06b4-11e8-85f0-1c49a0f720a4.png)
![image](https://user-images.githubusercontent.com/14765535/35624430-f313ddb2-06b4-11e8-81c4-09e9c93f14d9.png)

**Comment by Moulick** [comment]
https://tensorflow.org now automatically redirects to https://www.tensorflow.org. This issue can be closed
