### ISSUE TITLE
recurrent_network.py Linear Activation

### ISSUE THREAD

**Issue by djkim117** [aymericdamien/TensorFlow-Examples#27]
Hi, I am a little confused. 

in the def RNN function, you perform a linear activation of 
_X = tf.matmul(_X, _weights['hidden']) + _biases['hidden']

than, pass it in as input. 

Is that normal ? Isn't there only weight and bias for the 4 gates ?

**Comment by aymericdamien** [comment]
Hi, 
The reason is that it was getting somewhat better performances with it. But you can remove it, and it will still works fine. I understand it might be little confusing without further explanations, maybe it should be removed.

**Comment by djkim117** [comment]
Hi, I now see why you might have done it, thanks for letting me know, it would have bothered me for a while

your code helped a lot thank you.
