### ISSUE TITLE
MNIST input_data

### ISSUE THREAD

**Issue by hholst80** [aymericdamien/TensorFlow-Examples#28]
http://stackoverflow.com/questions/33664651/import-input-data-mnist-tensorflow-not-working

The fix described above works fine. Replace

    import input_data

with

    import tensorflow.examples.tutorials.mnist.input_data as input_data

**Comment by aymericdamien** [comment]
It seems that now Tensorflow sources also have 'input_data' file, so it is not require anymore. I am rewriting all examples, and they are all going to use tensorflow one directly.
