### ISSUE TITLE
convolutional_network_raw.ipynb doens't work for python3

### ISSUE THREAD

**Issue by seilgu** [aymericdamien/TensorFlow-Examples#328]
https://github.com/aymericdamien/TensorFlow-Examples/blob/master/tensorflow_v2/notebooks/3_NeuralNetworks/convolutional_network_raw.ipynb

`trainable_variables = weights.values() + biases.values()` doesn't work.
Also if I write `trainable_variables = list(weights.values()) + list(biases.values())`, I have to turn on `tf.enable_eager_execution()`, but the training result is wrong, accuracy is around 0.1 and not improving.

**Comment by youngvn** [comment]
Convert dict_values to list. It works well
trainable_variables = list(weights.values()) + list(biases.values())
