### ISSUE TITLE
Use cases for each algorithm

### ISSUE THREAD

**Issue by alexbilbie** [aymericdamien/TensorFlow-Examples#35]
I'm very new to machine learning and I've found this repository really useful.

I'm wondering if you could please add some notes to either the README or the individual examples detailing some example use cases that are appropriate for each algorithm?

**Comment by aymericdamien** [comment]
There are many different usage, but the most common:
- Convolutional network: learn a computer to classify images.
- Recurrent network : learn to classify sequences of data (such as text or audio).
- Neural network in general: Any classification or regression task .
- AutoEncoder: Encode/Decode data, it is similar to compression process, but you are more likely to lose information when decoding (see example notebook image to compare decoded images with their original).

**Comment by jdfweb** [comment]
Thanks for the info @aymericdamien !

**Comment by jgschmitz** [comment]
It could could also use vision and GPS to 'reserve' a lane for you on the road. Intelligent crowd planned roads and intersections would be safer.
