### ISSUE TITLE
change n_steps value in training and test

### ISSUE THREAD

**Issue by 987410** [aymericdamien/TensorFlow-Examples#36]
Hello, Aymeric Damien,

Thanks in advance

What I want to do is using different n_steps values in training and testing, How to set it?
for example, in current training n_steps = 16, however in test I want to use n_steps = 55 (or changed as various example). I reset n_steps =55 in test, but error happened:

tensorflow.python.framework.errors.InvalidArgumentError: Number of ways to split should evenly divide the split dimension, but got split_dim 0 (size = 55) and num_split 16

Thank you very much

Leo

**Comment by aymericdamien** [comment]
What you are looking for is RNNs with dynamic calculation, you need to change `rnn` function and set a 'sequence_length' argument that will represents a list of each sequence length in your batch.
For more info: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/rnn.py#57

**Comment by 987410** [comment]
Hi,

I used the code with _seq_len. Actually in training, n_steps (n_steps is global variable) is set constantly as 16, so as in your code there will be a vector _seq_len, and split with n_steps:

`    _seq_len = tf.fill(_batch_size, constant(_seq_len, dtype=tf.int32))
    _seq_len = tf.cast(_seq_len, dtype=tf.int64) #seq_len needs type int64..
...
...
    _X = tf.split(0,n_steps, _X) # n_steps * (batch_size, n_hidden)
`

but when testing,  how can i change this n_steps value into 55 in tf.split? does it make sense?

**Comment by 987410** [comment]
my problem maybe less complicated, because when training n_steps is constant, What I want to do is just change n_steps values when test

**Comment by lmolhw5252** [comment]
hello, Did your problem solved?
