### ISSUE TITLE
RNN examples - unused 'hidden' variables

### ISSUE THREAD

**Issue by PanTomaszRoszczynialski** [aymericdamien/TensorFlow-Examples#41]
Link to the definition of a dictionary holding variables in question:

https://github.com/aymericdamien/TensorFlow-Examples/blob/master/examples/3_NeuralNetworks/recurrent_network.py#L42

those variables seem to not be used anywhere, and code runs properly (i think) without them. Is there something I am missing or are those some kind of obsolete developement artifacts?

**Comment by aymericdamien** [comment]
Hi, this is a typo, it was based on the old example, but in this new one I removed the custom hidden states. Thanks for reporting that, I will update the code.
