### ISSUE TITLE
recurrent_network.py

### ISSUE THREAD

**Issue by kecaiwu** [aymericdamien/TensorFlow-Examples#42]
The comments of x=tf.split(0,n_steps,x) is 'split to get a list of 'n_steps' tensors of shape(batch_size,n_hidden)', the shape is (batch_sizs,n_hidden)? why not the (batch_size,n_input). Do i missing something?

**Comment by aymericdamien** [comment]
Yes, it is a typo, it should be `(batch_size,n_input)`, this is fixed now :)
