### ISSUE TITLE
TensorFlow-Examples/notebooks/3_NeuralNetworks/convolutional_network.ipynb is there an error or I'm just getting it false ?

### ISSUE THREAD

**Issue by AttilaZz** [aymericdamien/TensorFlow-Examples#47]
I'm trying to understand the layer in this CNN  by i'm not getting rigth the last number "5" in :

`# 5x5 conv, 32 inputs, 64 outputs`
`'wc2': tf.Variable(tf.random_normal([5, 5, 32, 5])),` 

since we have 64 output, is it supposed to be like this instead ? :
`'wc2': tf.Variable(tf.random_normal([5, 5, 32, 64])),`

**Comment by aymericdamien** [comment]
Yes, it is 64
https://github.com/aymericdamien/TensorFlow-Examples/blob/master/examples/3_NeuralNetworks/convolutional_network.py#L79

I am not sure where did you find it was 5? The examples are all set to 64.

**Comment by AttilaZz** [comment]
Strange cuz it was 5 last day, any way now it makes sense thanks a lot.
