### ISSUE TITLE
Importing RNN doesn't work any more with TensorFlow 0.9

### ISSUE THREAD

**Issue by zuoxingdong** [aymericdamien/TensorFlow-Examples#49]
Since the old importing files for rnn and rnn_celll are deprecated for latest version of TensorFlow. 

There is no need to import anymore, it can be called directly with `tf.nn.rnn()`

**Comment by aymericdamien** [comment]
arf yes, they changed it, I should fix that soon

**Comment by aymericdamien** [comment]
fixed
