### ISSUE TITLE
failed in running bidirectional_rnn

### ISSUE THREAD

**Issue by qinglintian** [aymericdamien/TensorFlow-Examples#88]
using tensorflow 0.12, it seems that tensorflow.contrib don't have modules like BasicLSTMCell and static_bidirectional_rnn

in 3_NeuralNetworks/bidirectional_rnn.py, line 67, 69, 73 and 76

**Comment by normanheckscher** [comment]
master branch requires TF 1.0 alpha

**Comment by ruzrobert** [comment]
Yes, works on TF 1.0.0-rc0.
But I am talking about recurrent_network.py , but I think, that bidirectional_rnn.py is working too.

**Comment by qinglintian** [comment]
thanks.
