### ISSUE TITLE
Bi-Directional LSTM

### ISSUE THREAD

**Issue by shoaibahmed** [aymericdamien/TensorFlow-Examples#9]
Thanks for sharing this valuable resource. The recurrent network example was very useful to me for sequence classification.
Can you pl add a new example which is same as recurrent_network.py but uses Bi-Directional LSTM instead of uni-directional. That will be very useful for me.
Thanks once again.

**Comment by aymericdamien** [comment]
I added bidirectional rnn example: https://github.com/aymericdamien/TensorFlow-Examples/blob/master/examples/3%20-%20Neural%20Networks/bidirectional_rnn.py
You can have a look.

**Comment by shoaibahmed** [comment]
I wrote the same code. Thanks.
There is one correction on line 59 (bidirectional_rnn.py):
_seq_len = tf.fill([_batch_size], constant(_seq_len, dtype=tf.int64))
tf is missing as it should be tf.constant.

**Comment by aymericdamien** [comment]
Ok! I close the issue then.
About tf.constant, I directly import constant at line: "from tensorflow.python.ops.constant_op import constant", but I agree that using tf.constant directly would be less confusing.

**Comment by shoaibahmed** [comment]
Can you pl also guide regarding how to port this Bi-Directional LSTM model on Android?
