### ISSUE TITLE
hello tensorflow

### ISSUE THREAD

**Issue by Mehak144** [aymericdamien/TensorFlow-Examples#92]
hi,
 I am running my first programe in spyder IDE,   
****from __future__ import print_function
import tensorflow as tf
hello = tf.constant('Hello, TensorFlow!')
sess = tf.Session()
print(sess.run(hello))****
 
 Th following error occur. 
 File "C:/Users/srprotech/Desktop/thesis/Spyder Practice/Hello world.py", line 9, in <module>
    import tensorflow as tf

ImportError: No module named 'tensorflow'
Please guide.

**Comment by Jimchen1218** [comment]
tensorflow need to be setup first.3ks.

**Comment by Mehak144** [comment]
Please guide me about setup procedure.

**Comment by swapnil-ss** [comment]
@Mehak144  you can install tensorflow by using the following command on the command prompt or terminal : 
$ sudo pip install tensorflow
or 
$ pip install tensorflow 
or you can refer to the link : 
https://www.tensorflow.org/get_started/os_setup

**Comment by kingburrito666** [comment]
You may also want to consider using pip3 as it is for python 3.x+
`sudo easy_install pip3`
then 
`sudo pip3 install tensorflow`
if you have GPU's 
`sudo pip3 install tensorflow-gpu`
